export const permissionsList = [
  { name: "Cash Register", value: "cashregister" },
  { name: "Customers", value: "customers" },
    { name: "Add Customer", value: "addcustomer" },
    { name: "Customer Detail", value: "customerdetail" },
    { name: "Customer Khata Detail", value: "customerkhatadetail" },
    { name: "Modify Customer", value: "modifycustomer" },
    { name: "Modify Customer Form", value: "modifycustomerform" },
    { name: "Delete Customer", value: "deletecustomer" },

    { name: "Customers Groups", value: "customergroup" },
    { name: "Create Customer Group", value: "createcustomergroup" },
    { name: "Modify | Delete C-Group", value: "modifydeletecustomergroup" },

  { name: "Dashboard", value: "dashboard" },
    { name: "blacklist", value: "blacklist" },
  { name: "Day Close", value: "dayclose" },
    { name: "Load Data From File", value: "loaddatafromfile" },
  { name: "Khata Entry", value: "khataentry" },
  { name: "Management", value: "management" },
    { name: "Add Products", value: "addproducts" },
    { name: "Categories", value: "categories" },
    { name: "Modify Products", value: "modifyproducts" },
      { name: "Modify Products Form", value: "modifyproductsform" },
    { name: "Payment Methods", value: "paymentmethods" },
    { name: "Pending Products", value: "pendingproducts" },
    { name: "products", value: "products" },
    { name: "Sale Types", value: "saletypes" },
    { name: "Stock", value: "stock" },
    { name: "Stock Detail", value: "stockdetail" },
  { name: "POS", value: "pos" },
    { name: "Expense", value: "expense" },
    { name: "Loss", value: "loss" },
    { name: "Purchase", value: "purchase" },
    { name: "Refund", value: "refund" },
    { name: "Sale", value: "sale" },
    { name: "Search Bills", value: "searchbills" },
    { name: "Stock Return", value: "stockreturn" },
  { name: "Reports", value: "reports" },
  { name: "Shops", value: "shops" },
    { name: "Create Shop", value: "createshop" },
    { name: "Modify Shop", value: "modifyshop" },
    { name: "Modify Shop Form", value: "modifyshopform" },
    { name: "Delete Shop", value: "deleteshop" },
  { name: "Updates", value: "updates" },
  { name: "Users", value: "users" },
    { name: "Create User", value: "createuser" },
    { name: "Modify User", value: "modifyuser" },
    { name: "Modify User Form", value: "modifyuserform" },
    { name: "Delete User", value: "deleteuser" },
    
  ];
  